<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">		
<dict>
	<!-- You must identify the plist as a CLM: -->
	<key>BBEditDocumentType</key>
	<string>CodelessLanguageModule</string>
	
	<!-- You must identify your language: -->
	<key>BBLMLanguageDisplayName</key>
	<string>Dockerfile</string>
	<key>BBLMLanguageCode</key>
	<string>DocF</string>
	
	<key>BBLMColorsSyntax</key>
	<true/>
	
	<key>BBLMKeywordList</key>
	<array>
		<string>FROM</string>
		<string>ARG</string>
		<string>ENV</string>
		<string>RUN</string>
		<string>COPY</string>
		<string>CMD</string>
	</array>
	
	<key>BBLMFileNamesToMatch</key>
	<array>
	    <string>Dockerfile</string>
	</array>
	
	<key>BBLMCommentLineDefault</key>
	<string>#</string>
	
	<key>Language Features</key>
	<dict>
		<key>Identifier and Keyword Character Class</key>
		<string>A-Za-z0-9_\?!</string>
		<key>Open Line Comments</key>
		<string>#</string>
		<key>Open Strings 1</key>
		<string>"</string>
	</dict> 
</dict>
</plist>